### ISSUE TITLE
[feature] Should set mark before jumping

### ISSUE THREAD

**Issue by Fuco1** [syohex/emacs-helm-gtags#93]
Global if we jump to a different file, local if we jump to a definition in the same source file.  This helps us to get back to from where we jumped easily.

**Comment by tuhdo** [comment]
You use `helm-gtags-pop-stack` to get back. I binded it to `M-,`, which is next to `M-.` for `helm-gtags-dwim`.

**Comment by Fuco1** [comment]
Is there some reason why are the marks reinvented?

**Comment by tuhdo** [comment]
Because  other marks won't mess with specialized marks for `helm-gtags`. When I jump in, I expect to use one keystroke to jump out. But if you use normal mark rings, you may have to press a lot (of course you have `helm-mark-rings` since we are using helm here), but this is more convenient: `M-.` jumps in, look around and during this process a few marks might be set, `M-,` jumps back to where you were. It gets more useful if you navigate deeper.

**Comment by syohex** [comment]
@Fuco1 You can use `helm-gtags-pop-stack`(or 'helm-gtags-previous-history and `'helm-gtags-next-history`) for this purpose. Emacs and many plugins often sets mark, so we cannot jump to
previous point at one time if we use some commands which set mark after tag jumping.

**Comment by Fuco1** [comment]
Fair enough, though I still think we should try to support the built-in systems whenever possible.  You never know what workflows some people use :)

As there is *a* solution this is not so pressing, but I would like to see it implemented sometime in the future anyway.  Often I only "tag jump" and then right back, and it's in my muscle memory to hit the "go to previous mark" button, so to decide if I jumped there with helm or some other thing is confusing and slows me down a bit.

Thanks for explaining your reasoning, I can agree with that.
